# Maven
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- task: UniversalPackages@0
  inputs:
    command: 'download'
    downloadDirectory: '$(Build.ArtifactStagingDirectory)'
    feedsToUse: 'internal'
    vstsFeed: '24909f86-8d03-4826-8947-55d471b47b72/57273a34-95c4-4b34-8b08-4600b3975070'
    vstsFeedPackage: '2bbe8cd3-9fee-41e9-9726-d3d2c93dc2bb'
    vstsPackageVersion: '*'
  displayName: load latest ORM version
- task: CmdLine@2
  inputs:
    script: |
      echo "contents:"
      
      ls $(Build.ArtifactStagingDirectory)

- task: MavenAuthenticate@0
  inputs:
    artifactsFeeds: 'Flock-of-Hawks-Artifacts'
  displayName: Authenticate Flock-of-Hawks-Artifacts with Maven
  
- task: Maven@3
  inputs:
    mavenPomFile: 'pom.xml'
    goals: 'install:install-file'
    options: > 
      -Dfile="$(Build.ArtifactStagingDirectory)/eorm-1.0.jar" 
      -DgroupId="org.example" 
      -DartifactId="eorm" 
      -Dversion="1.0" 
      -Dpackaging=jar 
      -DgeneratePom=true'
    publishJUnitResults: false
    javaHomeOption: 'JDKVersion'
    mavenVersionOption: 'Default'
    mavenAuthenticateFeed: false
    effectivePomSkip: false
    sonarQubeRunAnalysis: false
  displayName: provide the ORM dependency

- task: CmdLine@2
  inputs:
    script: 'mvn clean package && mvn install'
  displayName: Ensure dependencies are installed

- task: Maven@3
  inputs:
    mavenPomFile: 'pom.xml'
    publishJUnitResults: true
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
    javaHomeOption: 'JDKVersion'
    mavenVersionOption: 'Default'
    mavenAuthenticateFeed: false
    effectivePomSkip: false
    sonarQubeRunAnalysis: false
  displayName: package the WebApp
