# Maven
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- task: UniversalPackages@0
  inputs:
    command: 'download'
    downloadDirectory: '$(Pipeline.Workspace)/s/'
    feedsToUse: 'internal'
    vstsFeed: '24909f86-8d03-4826-8947-55d471b47b72/57273a34-95c4-4b34-8b08-4600b3975070'
    vstsFeedPackage: '2bbe8cd3-9fee-41e9-9726-d3d2c93dc2bb'
    vstsPackageVersion: '*'
  displayName: load latest ORM version

- task: Maven@3
  inputs:
    mavenPomFile: 'pom.xml'
    publishJUnitResults: true
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
    javaHomeOption: 'JDKVersion'
    mavenVersionOption: 'Default'
    mavenAuthenticateFeed: false
    effectivePomSkip: false
    sonarQubeRunAnalysis: false
  displayName: package the Webapp
