# Maven
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
- dev

pool:
  vmImage: ubuntu-latest

variables:
- group: Keys

steps:
- task: UniversalPackages@0
  inputs:
    command: 'download'
    downloadDirectory: '$(Build.ArtifactStagingDirectory)'
    feedsToUse: 'internal'
    vstsFeed: '24909f86-8d03-4826-8947-55d471b47b72/57273a34-95c4-4b34-8b08-4600b3975070'
    vstsFeedPackage: '2bbe8cd3-9fee-41e9-9726-d3d2c93dc2bb'
    vstsPackageVersion: '*'
  displayName: load latest ORM version

# - task: Bash@3
#   displayName: Create settings.xml file
#   inputs:
#     targetType: 'inline'
#     script: |
#       set -e
#       mkdir ~/.m2/
#       echo '<settings xmlns="http://maven.apache.org/SETTINGS/1.0.0"
#               xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
#               xsi:schemaLocation="http://maven.apache.org/SETTINGS/1.0.0
#                               https://maven.apache.org/xsd/settings-1.0.0.xsd">
#               <servers>
#                   <server>
#                       <id>Flock-of_Hawks-Artifacts</id>
#                       <username>revature-training-uta</username>
#                       <password>$(maven_key)</password>
#                   </server>
#               </servers>
#       </settings>' > ~/.m2/settings.xml
- task: CmdLine@2
  inputs:
    script: |
      echo $(Build.ArtifactStagingDirectory)
      ls $(Build.ArtifactStagingDirectory)
  displayName: Show contents of Artifact Staging Directory
- task: CmdLine@2
  inputs:
    script: 
      mvn install:install-file -e \
      -Dfile="$(Build.ArtifactStagingDirectory)/eorm-1.0.jar" \
      -DgroupId="org.example" \
      -DartifactId="eorm" \
      -Dversion="1.0" \
      -Dpackaging=jar \
      -DgeneratePom=true
  displayName: add orm jar file to maven packages

# - task: MavenAuthenticate@0
#   inputs:
#     artifactsFeeds: 'Flock-of-Hawks-Artifacts'
#   displayName: Authenticate Flock-of-Hawks-Artifacts with Maven

- task: Maven@3
  inputs:
    mavenPomFile: 'pom.xml'
    publishJUnitResults: true
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
    javaHomeOption: 'JDKVersion'
    mavenVersionOption: 'Default'
    mavenAuthenticateFeed: false
    effectivePomSkip: false
    sonarQubeRunAnalysis: false
  displayName: package the WebApp
