# Use Ansible to deploy Project 0 to VMs 2-5
# Tests are part of the Ansible Playbooks
# The deployP0.yml playbook calls all relevant playbooks

# Trigger the pipeline when the azure-pipelines branch gets a new push
trigger:
- dev

# We have the latest ubuntu as our base layer
pool:
  vmImage: ubuntu-latest

steps:

- task: SonarCloudPrepare@1
  inputs:
    SonarCloud: 'revature_sonarcloud'
    organization: '2105-may24-devops'
    scannerMode: 'CLI'
    configMode: 'manual'
    cliProjectKey: '2105-may24-devops_jacob-project0'
    cliProjectVersion: 
    cliSources: '.'

- task: SonarCloudAnalyze@1

- task: SonarCloudPublish@1
  inputs:
    pollingTimeoutSec: '300'

# Add the SSH key needed to access the VMs
- task: InstallSSHKey@0
  inputs:
    knownHostsEntry: |
      20.97.12.217 ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIDN4l2Jv2Krgw9EN21HHWfXGAoHZx/zHX5C0Iq9Ov/UU
      20.97.12.217 ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQC+OrY0VO+gD8eFk3wmVBY9McSOniH83A0mEM6kHeYQMpKNKbuar/DVBjkgz1sgfmrWLHZOPhDno96Av+1M6cPmKTEMsjWSaepPDCHxlO82RTR72h1zMy8UwimI5+AFCbehprRymLT3WJoTo2lgnQO0ZA6sCrwYhgnJVY1Yereb1lBmaS5vBJ4OVVb1l1VAdGnYVhYT44dfsEnlcFpjF4JAtH3RNUrGAJ89g9KXSSlv/6UshB+VAJ2M5kmvH/JReOuMIxnBGa/JYNCqYuUj4dj+EYYFszlpfwcHoSlUD7Laqc0yNQHSge0zVbdy/aeFxY0M/8jlF/1AU8bywBOGuWlx
      20.97.12.217 ecdsa-sha2-nistp256 AAAAE2VjZHNhLXNoYTItbmlzdHAyNTYAAAAIbmlzdHAyNTYAAABBBFAZU4nQNS6lNWqiFzoQ4pjTSmsGyxWmyoZS7pzSWooaua/yV9JDou49KuhCzZakpP/PY0WfTxbo/KrZM+ESW+Q=
    sshKeySecureFile: '2105-may24-devops-ubuntu-vm-1_key.pem'
  displayName: 'SSH--> Install Key'

# Run the playbook to deploy P0 to the VMs
- task: Ansible@0
  inputs:
    ansibleInterface: 'agentMachine'
    playbookPathOnAgentMachine: 'deployP1_docker.yml'
    inventoriesAgentMachine: 'file'
    inventoryFileOnAgentMachine: 'inventory.yml'
  displayName: 'Ansible--> Ensure Python 3.9'
