# using docker-compose version 3
version: '3'

# start containers for these networked services
services:

  # the postgres database back-end for the airport database
  airport_db:
    container_name: airport_postgres_db
    
    # use the latest version of the postgres image
    image: postgres:latest

    # always try to restart the database rather than kill and recreate
    restart: always

    # set the username/password environment variables
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password123
    
    # set up a named volume so that the database will persist
    # even if the container is erased
    volumes:
      - airport_db_volume:/var/lib/postgresql/data
  
  # the pgadmin database front-end that will run in the browser
  pgadmin:
    container_name: pgadmin4
    
    # use the latest imabe of pgadmin4
    image: dpage/pgadmin4:latest

    # always try to restart the database rather than kill and recreate
    restart: always

    # set the username/password environment variables
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin

    # set the outer:inner ports (remember Beoing 737)
    ports:
    - 737:80

# define the volume used for database persistance
volumes:
  airport_db_volume:
    driver: local
