# Maven
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
- main

pool:
  vmImage: ubuntu-latest

variables:
- group: Keys

steps:
- task: UniversalPackages@0
  inputs:
    command: 'download'
    downloadDirectory: '$(Build.ArtifactStagingDirectory)'
    feedsToUse: 'internal'
    vstsFeed: '24909f86-8d03-4826-8947-55d471b47b72/57273a34-95c4-4b34-8b08-4600b3975070'
    vstsFeedPackage: '2bbe8cd3-9fee-41e9-9726-d3d2c93dc2bb'
    vstsPackageVersion: '*'
  displayName: load latest ORM version

- task: CmdLine@2
  inputs:
    script: |
      mvn install:install-file -e \
      -Dfile="$(Build.ArtifactStagingDirectory)/eorm-1.0.jar" \
      -DgroupId="eteam" \
      -DartifactId="eorm" \
      -Dversion="1.0" \
      -Dpackaging=jar \
      -DgeneratePom=true
  displayName: add orm jar file to maven packages

- task: SonarQubePrepare@4
  inputs:
    SonarQube: 'VM3 SonarQube'
    scannerMode: 'Other'
    extraProperties: |
      # Additional properties that will be passed to the scanner,
      # Put one key=value per line, example:
      # sonar.exclusions=**/*.bin
      sonar.projectKey=Flock_of_Hawks_team_e_p1_webapp

- task: Maven@3
  inputs:
    mavenPomFile: 'pom.xml'
    publishJUnitResults: true
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
    javaHomeOption: 'JDKVersion'
    mavenVersionOption: 'Default'
    mavenAuthenticateFeed: false
    effectivePomSkip: false
    sonarQubeRunAnalysis: false
  displayName: package the WebApp

- task: SonarQubePublish@4
  inputs:
    pollingTimeoutSec: '300'

- task: ado-discord-webhook@1
  inputs:
    channelId: '856747431500447755'
    webhookKey: 'pnX9mrDlsv86zWC7VMmGQfR9vhvwEGqxWGJjDKyEXltzpPmzwTnC-zz85drbHeZaxw3C'
    name: '$(System.TeamProject) --> '
    avatar: 'https://avatarfiles.alphacoders.com/565/thumb-1920-56514.jpg'
    messageType: 'content'
    content: |
      __**$(Build.DefinitionName)**__
      **Build:** $(Build.BuildNumber)
      **Reason:** $(Build.Reason)
      **Status:** $(Agent.JobStatus)
      **Repo:** $(Build.Repository.Uri)
      **Message:** $(Build.SourceVersionMessage)
  condition: always()
  displayName: send message to Discord 
