# Builds and deploys the ORM .jar artifact on pushes to dev or main

trigger:
- main
- dev

variables:
  group: Keys
  image_repo: 'jpbulloch5/revature_p1_webapp'
  orm_version: 'latest'

pool:
  vmImage: ubuntu-latest

stages:
- stage: build
  jobs:
  - job: build
    steps:
    - task: UniversalPackages@0
      inputs:
        command: 'download'
        downloadDirectory: '$(Build.ArtifactStagingDirectory)'
        feedsToUse: 'internal'
        vstsFeed: '24909f86-8d03-4826-8947-55d471b47b72/57273a34-95c4-4b34-8b08-4600b3975070'
        vstsFeedPackage: 'b15fe07f-0110-4392-969b-957fa4eae94a'
        vstsPackageVersion: '*'
      displayName: Load latest ORM Artifact --> Task
    
    - task: CmdLine@2
      inputs:
        script: |
          mvn install:install-file -e \
          -Dfile="$(Build.ArtifactStagingDirectory)/eorm-1.0.jar" \
          -DgroupId="eteam" \
          -DartifactId="eorm" \
          -Dversion="1.0" \
          -Dpackaging=jar \
          -DgeneratePom=true
      displayName: Add ORM artifact to Maven packages --> Task
    
    - task: SonarCloudPrepare@1
      inputs:
        SonarCloud: 'SonarCloud'
        organization: 'isaac-revature-training-uta'
        scannerMode: 'Other'
        extraProperties: |
          # Additional properties that will be passed to the scanner,
          # Put one key=value per line, example:
          # sonar.exclusions=**/*.bin
          sonar.projectKey=revature-training-uta_team_e_p1_webapp
          sonar.projectName=team_e_p1_webapp
      displayName: Prepare Analysis --> Task
    - task: Maven@3
      inputs:
        mavenPomFile: 'pom.xml'
        publishJUnitResults: true
        testResultsFiles: '**/surefire-reports/TEST-*.xml'
        codeCoverageToolOption: 'JaCoCo'
        codeCoverageClassFilesDirectories: 'src/main/java/com/revature/airline/controller,dtos,repos,serializers,services,servlets,utils'
        javaHomeOption: 'JDKVersion'
        mavenVersionOption: 'Default'
        mavenAuthenticateFeed: false
        effectivePomSkip: false
        sonarQubeRunAnalysis: true
        isJacocoCoverageReportXML: true
        sqMavenPluginVersionChoice: 'latest'
        checkStyleRunAnalysis: true
        pmdRunAnalysis: true
        findBugsRunAnalysis: true
      displayName: Package WebApp war file; run analysis --> Task
      
    - task: SonarCloudPublish@1
      inputs:
        pollingTimeoutSec: '300'  
      displayName: Publish Analysis to SonarCloud --> Task

    - task: UniversalPackages@0
      inputs:
        command: 'publish'
        publishDirectory: '$(Build.SourcesDirectory)/target/p1-webapp-0.9.war'
        feedsToUsePublish: 'internal'
        vstsFeedPublish: '24909f86-8d03-4826-8947-55d471b47b72/57273a34-95c4-4b34-8b08-4600b3975070'
        vstsFeedPackagePublish: 'p1-webapp-0.9.war'
        versionOption: 'patch'
        packagePublishDescription: 'p1-webapp-0.9.war'
        verbosity: 'Debug'
        publishedPackageVar: 'webapp_artifact_name'
      displayName: Publish p1-webapp-0.9.war as a Universal Packages Artifact --> Task

    - task: PublishBuildArtifacts@1
      inputs:
        PathtoPublish: '$(Build.ArtifactStagingDirectory)'
        ArtifactName: 'p1-webapp-0.9.war'
        publishLocation: 'Container'
      displayName: Publish p1-webapp-0.9.war as a Build Artifact --> Task

    displayName: Build and Test WebApp --> Job

  - job: dockerize
    dependsOn: []
    steps:
    - task: Docker@2
      inputs:
        containerRegistry: 'Jacob''s Docker Hub'
        repository: $(image_repo)
        command: 'build'
        Dockerfile: '**/Dockerfile'
        tags: |
          $(orm_version)-$(Build.BuildId)
          latest_dev
        arguments: '--build-arg orm_version=$(orm_version)'
      condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/dev'))
      displayName: Build WebApp container --> Task
      
    - task: Docker@2
      inputs:
        containerRegistry: 'Jacob''s Docker Hub'
        repository: $(image_repo)
        command: 'build'
        Dockerfile: '**/Dockerfile'
        tags: |
          $(orm_version)-$(Build.BuildId)
          latest
        arguments: '--build-arg orm_version=$(orm_version)'
      condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/main'))
      displayName: Build WebApp container --> Task

    - task: Docker@2
      inputs:
        containerRegistry: 'Jacob''s Docker Hub'
        repository: '$(image_repo)'
        command: 'push'
        tags: |
          $(orm_version)-$(Build.BuildId)
          latest_dev
      condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/dev'))
      displayName: Push dev WebApp image to DockerHub --> Task

    - task: Docker@2
      inputs:
        containerRegistry: 'Jacob''s Docker Hub'
        repository: '$(image_repo)'
        command: 'push'
        tags: |
          $(orm_version)-$(Build.BuildId)
          latest
      condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/main'))
      displayName: Push main WebApp image to DockerHub --> Task
      
    - task: PublishBuildArtifacts@1
      inputs:
        PathtoPublish: '$(System.DefaultWorkingDirectory)/docker-compose.yml'
        ArtifactName: 'docker-compose.yml'
        publishLocation: 'Container'
      displayName: Publish docker-compose.yml file
    
    displayName: Build and Push WebApp Docker image --> Job
  displayName: Build, Test, and Push WebApp Docker image --> Stage

- stage: test
  dependsOn:
  - build
  jobs:
  - job: test
    steps:
    
    - task: DockerCompose@0
      inputs:
        containerregistrytype: 'Container Registry'
        dockerRegistryEndpoint: 'Jacob''s Docker Hub'
        dockerComposeFile: '**/docker-compose.yml'
        action: 'Run a Docker Compose command'
        dockerComposeCommand: 'up'
        arguments: '-d'
      displayName: Start Dockerized application network --> Task

    - task: CmdLine@2
      inputs:
        script: 'docker cp airline_terminal:/app/web/P1_Local_Postman_Collection.json ./local_test.json'
        failOnStderr: true
      displayName: Fetch test from container --> Task
      
    - task: CmdLine@2
      inputs:
        script: 'docker cp airline_terminal:/app/web/docker-compose.yml $(Build.ArtifactStagingDirectory)/docker-compose.yml'
        failOnStderr: true
      displayName: Fetch the docker compose file from the container

    - task: PublishBuildArtifacts@1
      inputs:
        PathtoPublish: '$(Build.ArtifactStagingDirectory)'
        ArtifactName: 'docker-compose.yml'
        publishLocation: 'Container'
      displayName: Publish the docker compose file as an artifact
    
    - task: NewmanPostman@4
      inputs:
        collectionSourceType: 'file'
        Contents: '**/local_test.json'
        environmentSourceType: 'none'
        bail: true
        reporters: 'junit'
      displayName: Run Newman Postman function test --> Task

    displayName: Run dev's fucnction test --> Job
  displayName: Run dev's fucnction test --> Stage

- stage: report
  dependsOn:
  - build
  - test
  jobs:
  - job: report
    steps:
    - checkout: none
    - task: ado-discord-webhook@1
      inputs:
        channelId: '856747431500447755'
        webhookKey: 'pnX9mrDlsv86zWC7VMmGQfR9vhvwEGqxWGJjDKyEXltzpPmzwTnC-zz85drbHeZaxw3C'
        name: '$(System.TeamProject) -->'
        avatar: 'https://avatarfiles.alphacoders.com/565/thumb-1920-56514.jpg'
        messageType: 'content'
        content: |
          __**$(Build.DefinitionName)**__
          **Image:** $(image_repo):$(Build.BuildId)
          **Branch:** $(Build.SourceBranch)
          **Build:** $(Build.BuildNumber)
          **Reason:** $(Build.Reason)
          **Status:** $(Agent.JobStatus)
          **Repo:** $(Build.Repository.Uri)
          **Message:** $(Build.SourceVersionMessage)
          _**Approval Required for Deployment to VM-3**_
          https://dev.azure.com/revature-training-uta/Flock%20of%20Hawks/_build/results?buildId=$(Build.BuildId)&view=results
      displayName: Publish build details to Discord --> Task
        
    displayName: Report build results --> Job
  displayName: Report build results --> Stage

- stage: deploy
  jobs:
  - deployment: deploy
    environment: 'production'
    strategy:
      runOnce:
        deploy:
          steps:
            
          - task: DownloadPipelineArtifact@2
            inputs:
              buildType: 'current'
              itemPattern: 'docker-compose.yml'
              targetPath: '$$(Build.ArtifactStagingDirectory)'

          - task: InstallSSHKey@0
            inputs:
              knownHostsEntry: |
                20.97.12.217 ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIDN4l2Jv2Krgw9EN21HHWfXGAoHZx/zHX5C0Iq9Ov/UU
                20.97.12.217 ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQC+OrY0VO+gD8eFk3wmVBY9McSOniH83A0mEM6kHeYQMpKNKbuar/DVBjkgz1sgfmrWLHZOPhDno96Av+1M6cPmKTEMsjWSaepPDCHxlO82RTR72h1zMy8UwimI5+AFCbehprRymLT3WJoTo2lgnQO0ZA6sCrwYhgnJVY1Yereb1lBmaS5vBJ4OVVb1l1VAdGnYVhYT44dfsEnlcFpjF4JAtH3RNUrGAJ89g9KXSSlv/6UshB+VAJ2M5kmvH/JReOuMIxnBGa/JYNCqYuUj4dj+EYYFszlpfwcHoSlUD7Laqc0yNQHSge0zVbdy/aeFxY0M/8jlF/1AU8bywBOGuWlx
                20.97.12.217 ecdsa-sha2-nistp256 AAAAE2VjZHNhLXNoYTItbmlzdHAyNTYAAAAIbmlzdHAyNTYAAABBBFAZU4nQNS6lNWqiFzoQ4pjTSmsGyxWmyoZS7pzSWooaua/yV9JDou49KuhCzZakpP/PY0WfTxbo/KrZM+ESW+Q=
              sshKeySecureFile: 'revature.pem'
            displayName: Authorize remote access to VM-3

          - task: CopyFilesOverSSH@0
            inputs:
              sshEndpoint: 'Revature VM3'
              sourceFolder: '$(Build.ArtifactStagingDirectory)'
              contents: 'docker-compose.yml'
              targetFolder: '/home/jacob/p1'
              readyTimeout: '20000'
          - task: SSH@0
            inputs:
              sshEndpoint: 'Revature VM3'
              runOptions: 'commands'
              commands: sudo docker-compose -f /home/jacob/p1/docker-compose.yml up --force-recreate -d
              failOnStdErr: false
              readyTimeout: '20000'
            displayName: Start Dockerized application on VM-3 --> Task
        
          - task: SSH@0
            inputs:
              sshEndpoint: 'Revature VM3'
              runOptions: 'commands'
              commands: |
                cd ~/p1
                sudo docker system prune -a -f --volumes
              failOnStdErr: false
              readyTimeout: '20000'
            displayName: Remove outdated Docker resources --> Task

          - task: ado-discord-webhook@1
            inputs:
              channelId: '856747431500447755'
              webhookKey: 'pnX9mrDlsv86zWC7VMmGQfR9vhvwEGqxWGJjDKyEXltzpPmzwTnC-zz85drbHeZaxw3C'
              name: '$(System.TeamProject) -->'
              avatar: 'https://avatarfiles.alphacoders.com/565/thumb-1920-56514.jpg'
              messageType: 'content'
              content: |
                __**$(Build.DefinitionName)**__
                **__DEPLOYING__**
                **Build:** $(Build.BuildNumber)
                **Status:** $(Agent.JobStatus)
            displayName: Publish deployment details to Discord --> Task

    displayName: Deploy to VM-3 using Docker --> Deployment
  displayName: Deploy with Docker --> Stage